### ISSUE TITLE
Does iink support desktop app?

### ISSUE THREAD

**Issue by frankzha** [MyScript/interactive-ink-examples-uwp#1]
on Windows 10, if I understand it correctly, currently iink only support UWP, not the traditional desktop app, is that correct? I wonder why it is bundled with uwp? Seems it should be neutral of the app type.

**Comment by thomaspenin** [comment]
From a technical point of view, UWP and the traditional Windows desktop environment are sensibly different, particularly for libraries where it involves wrapping native C++ code, like iink SDK. We focused on UWP first as it was the environment that most of our Windows customers were interested in. We are currently working on Windows desktop support, though, and it should land shortly.
