### ISSUE TITLE
I Can't handwirte math

### ISSUE THREAD

**Issue by dengbh** [MyScript/interactive-ink-examples-uwp#2]
I already download MyScript.InteractiveInk.Examples.Uwp to my pc.   run program,  but I can't handwrite math.    I think my Configuration is wrong.   Could you tell me what I have to do?

**Comment by MyScriptSupport** [comment]
Dear Dengbh,

thank you for contacting us.
Currently, in your code, you should set a "Math" part. You should also ensure the Math assets are installed.
Please note you can refer to the documentation: https://developer.myscript.com/docs/interactive-ink/1.3/windows/fundamentals/editing/#block-management

Best regards,
Olivier

**Comment by dengbh** [comment]
Text and mathematical formula can write together,   but not alone  write.  
   I want wirte text and mathematical formula  in Word.  Has you Sample code

**Comment by MyScriptSupport** [comment]
Dear Dengbh,

Currently, you can create a Text Document part with Math and Text blocks inside of it, then export it as word: https://developer.myscript.com/docs/interactive-ink/1.3/android/fundamentals/editing/#content-blocks.

Regarding the export, you can refer to the following part of the documentation: https://developer.myscript.com/docs/interactive-ink/1.3/android/fundamentals/import-and-export/#exporting-content

Best regards,

Olivier
